version: '3.4'

services:
  exampleapp:
    build:
      context: .
      dockerfile: AspNetCoreApiExample/Dockerfile
    container_name: exampleapp-container
    depends_on:
      - exampledb
  examplemigration:
    build:
      context: .
      dockerfile: ./Docker/migration/Dockerfile
    container_name: examplemigration-container
    depends_on:
      - exampledb
  examplenginx:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    container_name: examplenginx-container
    depends_on:
      - exampleapp
    restart: always
  exampledb:
    image: mysql:8
    container_name: exampledb-container
    volumes:
      - ./Docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - example-mysql:/var/lib/mysql
    # マウントした設定ファイルが644でないとエラー（Windowsでは777）になるので、起動前にパーミッションを変える
    entrypoint: "/bin/bash -c 'chmod 644 /etc/mysql/conf.d/* && docker-entrypoint.sh mysqld'"
    restart: always
volumes:
  example-mysql:
