version: '3.4'

services:
  exampleapp:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EXAMPLEAPP_DATABASE__CONNECTIONSTRING: "server=exampledb-container; port=3306; user=blog_usr; password=blog001; database=blog_db"
  examplemigration:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EXAMPLEAPP_DATABASE__CONNECTIONSTRING: "server=exampledb-container; port=3306; user=blog_usr; password=blog001; database=blog_db"
  examplenginx:
    ports:
      - 80:80
  exampledb:
    ports:
      - 3306:3306
  examplefluentd:
    ports:
      - 24224:24224
      - "24224:24224/udp"
