---
- name: Register .NET repository
  yum: name={{ dotnetsource }} state=present

- name: Install .NET Core 3.1
  yum: name=dotnet-sdk-3.1 state=latest

- block:
  - name: Check dotnet-ef installed
    shell: dotnet tool list -g | grep -e "^dotnet-ef "
    register: dotnetef_installed
    check_mode: no
    changed_when: false
    failed_when: false
  - name: Install dotnet-ef
    shell: dotnet tool install -g dotnet-ef --version 3.1.0
    when: dotnetef_installed.stdout == ""
  become: false
