app_nginx_conf_src: "nginx.conf.j2"
app_nginx_conf_dest: "/etc/nginx/default.d/vagrant.conf"
app_svr_dir: "/vagrant/AspNetCoreApiExample"
app_log_dir: "/var/log/local/aspnetcoreapi-example"
app_db:
  - blog_db
app_db_users:
  - user: blog_usr
    password: "blog001"
    privilege: "blog_db.*:ALL"
user: "nginx"
group: "nginx"
app_svr_service_name: "aspnetcore-example"
app_svr_service_src: "{{ app_svr_service_name }}.service.j2"
app_svr_service_dest: "/etc/systemd/system/{{ app_svr_service_name }}.service"
build_configuration: "Release"
app_svr_work_dir: "{{ app_svr_dir }}/bin/{{ build_configuration }}/netcoreapp2.1/publish"
app_svr_dll: "{{ app_svr_work_dir }}/AspNetCoreApiExample.dll"
app_environment: "Development"