---
- name: Check timezone
  shell: timedatectl | grep -e {{ timezone }}
  register: timedatectl_timezone
  check_mode: no
  changed_when: false
  failed_when: false
- name: Set timezone
  shell: timedatectl set-timezone {{ timezone }}
  when: timedatectl_timezone.stdout == ""
